### ISSUE TITLE
via version

### ISSUE THREAD

**Issue by pizzav-xyz** [gudenau/minecraft-wootingcraft#2]
would it be possible to make the lighting the keybinds with via or qmk?

**Comment by gudenau** [comment]
What are those?

**Comment by pizzav-xyz** [comment]
> What are those?

https://www.caniusevia.com/docs/specification

https://docs.qmk.fm

**Comment by gudenau** [comment]
The first link doesn't lead to anything and it appears as though the second one doesn't support analog keyboards? Without analog support it's out of scope for this mod.

**Comment by pizzav-xyz** [comment]
> The first link doesn't lead to anything and it appears as though the second one doesn't support analog keyboards? Without analog support it's out of scope for this mod.

updated, a lot of keyboards support qmk and via

**Comment by gudenau** [comment]
> > The first link doesn't lead to anything and it appears as though the second one doesn't support analog keyboards? Without analog support it's out of scope for this mod.
> 
> updated, a lot of keyboards support qmk and via

Do they support analog keyboards?
