### ISSUE TITLE
Java 21 Version

### ISSUE THREAD

**Issue by CommandGenius** [gudenau/minecraft-wootingcraft#3]
Could you make a Java 21 version of this mod? Many mods aren't supportive of Java 22.

**Comment by gudenau** [comment]
Incompatibilities other mods have with Java 22+ are issues with those mods, not this one. This mod uses features that where added in Java 22, hence the version requirement.

**Comment by CommandGenius** [comment]
I just checked, they work on Java 22 without the mod, but with the mod they stop working.
